### ISSUE TITLE
(multiplayer)Can't place Eeprom in computer case.

### ISSUE THREAD

**Issue by AlphaLlama** [Panakotta00/FicsIt-Networks#148]
Ctrl+double clicking the Eeprom in the inventory doesn't work, either. it's almost as though the slot suddenly disappeared from the cases all together. I checked the console after attempting and found this error seemed to pop up around that time: 

[2021.08.13-09.38.24:817][  0]LogGame: Warning: SetAllowedItemOnIndex failed cause invalid index (0) passed, component 'DataStorage'
[2021.08.13-09.38.24:818][  0]LogGame: Warning: SetAllowedItemOnIndex failed cause invalid index (1) passed, component 'DataStorage'" 

but i'm not sure if that's related. I've attached a log file if it might help.
[FactoryGame.log](https://github.com/Panakotta00/FicsIt-Networks/files/6981702/FactoryGame.log)

**Comment by Panakotta00** [comment]
Does drag'n'drop work?

I think it's half an issue,
shift-clicking on EEPROM only works when the EEPROM already got placed into a computer once. Because then the EEPROM will be connected with "data" and freshly crafted it is not... and I think currently the "shift-click" only works when this data is present.

If thats the case its a issue on low priority...

If you are even not able to place the EEPROM with drag'n'drop then thats a larger issue, are you trying to place it into the computer as client or as host, and have you placed a CPU before hand? Does it then properly show the editor view on the mentioned side and not the "CPU Not detected" warning?

**Comment by AlphaLlama** [comment]
I'm laying as a client on a dedicated server, Drag n drop doesn't work, double clicking, shift clicking, nothing works. I've built the case, placed the cpu and ram and then go to place a freshly crafted Eeprom and it's as if the socket for it doesn't exist. the odd thing is, hovering over the socket on the interface will give the description of the eeprom as if one was there, even though it never left my inventory. after all this, going back to the code screen still has the error of "No eeprom detected" and any attempt to start the computer still fails.

Transfering the save game to a single player game where all things are similar(mods installed and such) everything seems to work just fine. but if i add the eeprom in single player then transfer the save over to the server the eeprom just disappears, so it's looking like it's multiplayer only.

**Comment by Panakotta00** [comment]
I have done some MP fixes for the next update tho idk if that one is fixed now...
if you want... you can try to install the in-dev version

**Comment by Panakotta00** [comment]
If it still doesnt work, feel free to reopen the issue
