### ISSUE TITLE
Feature Request: Add ability to tab within the code editor

### ISSUE THREAD

**Issue by Justintime505** [Panakotta00/FicsIt-Networks#190]
would really like the ability to tab within the code editor. Currently I'm using an outside editor for the single reason that I have to use spaces to indent within the mod. This gets old when you're 4 layers deep in a for each loop. Adding this would probably eliminate the need to constantly be alt tabbing back and forth. And with the new reflection view I could do all my work within the game and not need to alt-tab at all. That would be fantastic.

**Comment by Panakotta00** [comment]
Sadly investigating on how to get Tabs working in the Unreal Text Editor is as hard as getting line numbers to work.
So right now there is no foreseable future were we plan to investigate this, especiall since the most common and best practice is to use for larger projects, and actual IDE with multiple files etc. by using the filesystem that is mirrored to the host system.
If your IDE of choice supports Emmy Lua (or as plugin, we reccomend IntelliJ) then you can checkout our (still early) Emmy Lua doc that allows for autocorrection etc. inside of the IDE
